import { Theme } from './types'

export const themes: Theme[] = [
  {
    id: 'qubria-dark',
    name: 'Qubria Dark',
    colors: {
      bg: '#0f1729',
      surface: '#1e293b',
      sidebar: '#0a1225',
      border: '#334155',
      text: '#ffffff',
      textDim: '#a8b5c7',
      accent: '#6366f1',
      accent2: '#38bdf8',
      accent3: '#a78bfa',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#f43f5e',
    },
    terminalColors: {
      background: '#0f1729',
      foreground: '#e2e8f0',
      cursor: '#6366f1',
      cursorAccent: '#0f1729',
      selectionBackground: '#6366f140',
      black: '#0f1729',
      red: '#f43f5e',
      green: '#10b981',
      yellow: '#f59e0b',
      blue: '#3b82f6',
      magenta: '#a78bfa',
      cyan: '#38bdf8',
      white: '#e2e8f0',
      brightBlack: '#64748b',
      brightRed: '#fb7185',
      brightGreen: '#34d399',
      brightYellow: '#fbbf24',
      brightBlue: '#60a5fa',
      brightMagenta: '#c4b5fd',
      brightCyan: '#7dd3fc',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'ghostshell-dark',
    name: 'Forge Ops',
    colors: {
      bg: '#141414',
      surface: '#1e1e1e',
      sidebar: '#0e0e0e',
      border: '#3a3a3a',
      text: '#f5f5f5',
      textDim: '#b4b4bc',
      accent: '#ff6b00',
      accent2: '#22d3ee',
      accent3: '#facc15',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    terminalColors: {
      background: '#141414',
      foreground: '#f3f4f6',
      cursor: '#ff6b00',
      cursorAccent: '#141414',
      selectionBackground: '#ff6b0038',
      black: '#0e0e0e',
      red: '#f87171',
      green: '#4ade80',
      yellow: '#facc15',
      blue: '#38bdf8',
      magenta: '#fb7185',
      cyan: '#22d3ee',
      white: '#f5f5f5',
      brightBlack: '#71717a',
      brightRed: '#fca5a5',
      brightGreen: '#86efac',
      brightYellow: '#fde047',
      brightBlue: '#7dd3fc',
      brightMagenta: '#f9a8d4',
      brightCyan: '#67e8f9',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Laser Grid',
    colors: {
      bg: '#0e1428',
      surface: '#182444',
      sidebar: '#0a1020',
      border: '#2d3d68',
      text: '#f5f7ff',
      textDim: '#9eabd4',
      accent: '#ff2bd6',
      accent2: '#00e7ff',
      accent3: '#c3ff2b',
      success: '#30ff9b',
      warning: '#ffbf3c',
      error: '#ff4d73',
    },
    terminalColors: {
      background: '#0e1428',
      foreground: '#eef4ff',
      cursor: '#00e7ff',
      cursorAccent: '#0e1428',
      selectionBackground: '#00e7ff33',
      black: '#0a1020',
      red: '#ff5c8a',
      green: '#3cfca2',
      yellow: '#ffe24a',
      blue: '#3da4ff',
      magenta: '#ff4bf1',
      cyan: '#00f5ff',
      white: '#eef4ff',
      brightBlack: '#6878a0',
      brightRed: '#ff8aa9',
      brightGreen: '#82ffc4',
      brightYellow: '#fff27a',
      brightBlue: '#7dc3ff',
      brightMagenta: '#ff8bff',
      brightCyan: '#7dffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'neon',
    name: 'Acid Wash',
    colors: {
      bg: '#0e2018',
      surface: '#162c24',
      sidebar: '#0a1810',
      border: '#2a5044',
      text: '#f3fff8',
      textDim: '#9ec9b8',
      accent: '#7dff5a',
      accent2: '#00d9ff',
      accent3: '#ffe45e',
      success: '#4cff9a',
      warning: '#ffc247',
      error: '#ff6177',
    },
    terminalColors: {
      background: '#0e2018',
      foreground: '#f4fff8',
      cursor: '#7dff5a',
      cursorAccent: '#0e2018',
      selectionBackground: '#7dff5a33',
      black: '#0a1810',
      red: '#ff6b81',
      green: '#55ff9e',
      yellow: '#ffe45e',
      blue: '#35c8ff',
      magenta: '#b58cff',
      cyan: '#00eaff',
      white: '#f4fff8',
      brightBlack: '#5f8174',
      brightRed: '#ff9aaa',
      brightGreen: '#8dffbc',
      brightYellow: '#fff08b',
      brightBlue: '#73dcff',
      brightMagenta: '#d2b5ff',
      brightCyan: '#79f4ff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'midnight',
    name: 'Abyss Signal',
    colors: {
      bg: '#0f1e30',
      surface: '#1c2d48',
      sidebar: '#0c1825',
      border: '#355478',
      text: '#edf6ff',
      textDim: '#9eb4ce',
      accent: '#61a8ff',
      accent2: '#2dd4bf',
      accent3: '#ff8d4d',
      success: '#38d39f',
      warning: '#ffb444',
      error: '#ff7285',
    },
    terminalColors: {
      background: '#0f1e30',
      foreground: '#edf6ff',
      cursor: '#61a8ff',
      cursorAccent: '#0f1e30',
      selectionBackground: '#61a8ff38',
      black: '#0c1825',
      red: '#ff8090',
      green: '#4ae0ae',
      yellow: '#ffc45c',
      blue: '#63b3ff',
      magenta: '#8fb8ff',
      cyan: '#33dfc9',
      white: '#edf6ff',
      brightBlack: '#647b98',
      brightRed: '#ffadb6',
      brightGreen: '#7bf0c2',
      brightYellow: '#ffd88d',
      brightBlue: '#91c7ff',
      brightMagenta: '#b4d0ff',
      brightCyan: '#72f1de',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'redline',
    name: 'Redline',
    colors: {
      bg: '#1e0e10',
      surface: '#301618',
      sidebar: '#160a0b',
      border: '#622830',
      text: '#fff1ef',
      textDim: '#d0a09e',
      accent: '#ff4d57',
      accent2: '#ffb347',
      accent3: '#ffe6a7',
      success: '#59d98e',
      warning: '#ffb347',
      error: '#ff4d57',
    },
    terminalColors: {
      background: '#1e0e10',
      foreground: '#fff3f0',
      cursor: '#ffb347',
      cursorAccent: '#1e0e10',
      selectionBackground: '#ff4d5738',
      black: '#160a0b',
      red: '#ff6b74',
      green: '#63e6a1',
      yellow: '#ffd166',
      blue: '#6aa7ff',
      magenta: '#ff8ba7',
      cyan: '#71e7ff',
      white: '#fff3f0',
      brightBlack: '#8a5052',
      brightRed: '#ff99a0',
      brightGreen: '#93efbd',
      brightYellow: '#ffe099',
      brightBlue: '#9bc2ff',
      brightMagenta: '#ffb0c3',
      brightCyan: '#9bf0ff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'monolith',
    name: 'Monolith',
    colors: {
      bg: '#131313',
      surface: '#1c1e22',
      sidebar: '#0c0d0e',
      border: '#404850',
      text: '#f5f7fa',
      textDim: '#a4adb8',
      accent: '#e5ecf4',
      accent2: '#7dd3fc',
      accent3: '#fb7185',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#fb7185',
    },
    terminalColors: {
      background: '#131313',
      foreground: '#f5f7fa',
      cursor: '#e5ecf4',
      cursorAccent: '#131313',
      selectionBackground: '#7dd3fc30',
      black: '#0c0d0e',
      red: '#fb7185',
      green: '#4ade80',
      yellow: '#fbbf24',
      blue: '#7dd3fc',
      magenta: '#f9a8d4',
      cyan: '#67e8f9',
      white: '#f5f7fa',
      brightBlack: '#767f8b',
      brightRed: '#fda4af',
      brightGreen: '#86efac',
      brightYellow: '#fde68a',
      brightBlue: '#bae6fd',
      brightMagenta: '#fbcfe8',
      brightCyan: '#a5f3fc',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'meridian-luxe',
    name: 'Meridian Luxe',
    colors: {
      bg: '#161618',
      surface: '#232328',
      sidebar: '#101012',
      border: '#484852',
      text: '#f7f4ee',
      textDim: '#c8c0b4',
      accent: '#d6b36a',
      accent2: '#7dd3c7',
      accent3: '#f59e7a',
      success: '#57d39b',
      warning: '#e9b44c',
      error: '#ef6f6c',
    },
    terminalColors: {
      background: '#161618',
      foreground: '#f7f4ee',
      cursor: '#d6b36a',
      cursorAccent: '#161618',
      selectionBackground: '#d6b36a33',
      black: '#101012',
      red: '#ef6f6c',
      green: '#57d39b',
      yellow: '#e9b44c',
      blue: '#89b4fa',
      magenta: '#d4a5ff',
      cyan: '#7dd3c7',
      white: '#f7f4ee',
      brightBlack: '#7e7e8c',
      brightRed: '#f4a09d',
      brightGreen: '#8ce4bb',
      brightYellow: '#f1ce7a',
      brightBlue: '#b0cbff',
      brightMagenta: '#e5c4ff',
      brightCyan: '#a9ece4',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'greenroom',
    name: 'Greenroom',
    colors: {
      bg: '#0e2015',
      surface: '#182c20',
      sidebar: '#0a180e',
      border: '#335540',
      text: '#edfff3',
      textDim: '#9ecaae',
      accent: '#5cff8d',
      accent2: '#00e0b8',
      accent3: '#d7ff5c',
      success: '#5cff8d',
      warning: '#ffd24a',
      error: '#ff6578',
    },
    terminalColors: {
      background: '#0e2015',
      foreground: '#edfff3',
      cursor: '#5cff8d',
      cursorAccent: '#0e2015',
      selectionBackground: '#5cff8d33',
      black: '#0a180e',
      red: '#ff6578',
      green: '#5cff8d',
      yellow: '#d7ff5c',
      blue: '#4dc4ff',
      magenta: '#8effd0',
      cyan: '#00f0c8',
      white: '#edfff3',
      brightBlack: '#648574',
      brightRed: '#ff97a4',
      brightGreen: '#95ffb4',
      brightYellow: '#e9ff93',
      brightBlue: '#86d8ff',
      brightMagenta: '#bcffe4',
      brightCyan: '#7dffe7',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'command-deck',
    name: 'Command Deck',
    colors: {
      bg: '#101e2e',
      surface: '#1c2d3e',
      sidebar: '#0e1822',
      border: '#3a5068',
      text: '#eef6ff',
      textDim: '#a0b5c8',
      accent: '#66aaff',
      accent2: '#ffb454',
      accent3: '#4fd1c5',
      success: '#4dd4a0',
      warning: '#ffb454',
      error: '#ff7285',
    },
    terminalColors: {
      background: '#101e2e',
      foreground: '#eef6ff',
      cursor: '#66aaff',
      cursorAccent: '#101e2e',
      selectionBackground: '#66aaff33',
      black: '#0e1822',
      red: '#ff7285',
      green: '#4dd4a0',
      yellow: '#ffb454',
      blue: '#66aaff',
      magenta: '#98b6ff',
      cyan: '#4fd1c5',
      white: '#eef6ff',
      brightBlack: '#6e8498',
      brightRed: '#ff9eaa',
      brightGreen: '#82e7be',
      brightYellow: '#ffd08a',
      brightBlue: '#9bc4ff',
      brightMagenta: '#c0d2ff',
      brightCyan: '#83e9de',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'hyperlane',
    name: 'Hyperlane',
    colors: {
      bg: '#141d2e',
      surface: '#1f2c3e',
      sidebar: '#0f1620',
      border: '#3d5068',
      text: '#eef5ff',
      textDim: '#a4b8d0',
      accent: '#78b7ff',
      accent2: '#69e5d1',
      accent3: '#ff9c7a',
      success: '#56ddb0',
      warning: '#ffbf69',
      error: '#ff7c8f',
    },
    terminalColors: {
      background: '#141d2e',
      foreground: '#eef5ff',
      cursor: '#78b7ff',
      cursorAccent: '#141d2e',
      selectionBackground: '#78b7ff30',
      black: '#0f1620',
      red: '#ff7c8f',
      green: '#56ddb0',
      yellow: '#ffbf69',
      blue: '#78b7ff',
      magenta: '#9ab0ff',
      cyan: '#69e5d1',
      white: '#eef5ff',
      brightBlack: '#70859e',
      brightRed: '#ffacb7',
      brightGreen: '#8aeaca',
      brightYellow: '#ffd69a',
      brightBlue: '#a9cfff',
      brightMagenta: '#c2ceff',
      brightCyan: '#97f0e2',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'transit-glass',
    name: 'Transit Glass',
    colors: {
      bg: '#151e28',
      surface: '#202a34',
      sidebar: '#101820',
      border: '#3e5060',
      text: '#f3f7fb',
      textDim: '#a8bac9',
      accent: '#7bdff2',
      accent2: '#f7a072',
      accent3: '#9be564',
      success: '#67dda8',
      warning: '#f7c66b',
      error: '#f88379',
    },
    terminalColors: {
      background: '#151e28',
      foreground: '#f3f7fb',
      cursor: '#7bdff2',
      cursorAccent: '#151e28',
      selectionBackground: '#7bdff230',
      black: '#101820',
      red: '#f88379',
      green: '#67dda8',
      yellow: '#f7c66b',
      blue: '#8db7ff',
      magenta: '#b8a1ff',
      cyan: '#7bdff2',
      white: '#f3f7fb',
      brightBlack: '#738292',
      brightRed: '#fbb0a9',
      brightGreen: '#95ebc2',
      brightYellow: '#fbdba0',
      brightBlue: '#bad1ff',
      brightMagenta: '#d5c6ff',
      brightCyan: '#a9edf8',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'velvet-obsidian',
    name: 'Velvet Obsidian',
    colors: {
      bg: '#131312',
      surface: '#1e1e20',
      sidebar: '#0c0c0d',
      border: '#44403a',
      text: '#f7f1e8',
      textDim: '#c8bcac',
      accent: '#d4af6a',
      accent2: '#8dd3c7',
      accent3: '#e8c39e',
      success: '#67d4a3',
      warning: '#e9bc62',
      error: '#ef7d7a',
    },
    terminalColors: {
      background: '#131312',
      foreground: '#f7f1e8',
      cursor: '#d4af6a',
      cursorAccent: '#131312',
      selectionBackground: '#d4af6a33',
      black: '#0c0c0d',
      red: '#ef7d7a',
      green: '#67d4a3',
      yellow: '#e9bc62',
      blue: '#9ab7ff',
      magenta: '#dfb3ff',
      cyan: '#8dd3c7',
      white: '#f7f1e8',
      brightBlack: '#7c7468',
      brightRed: '#f4a7a4',
      brightGreen: '#98e5be',
      brightYellow: '#f2d496',
      brightBlue: '#bfd2ff',
      brightMagenta: '#ebcbff',
      brightCyan: '#b8eee6',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'amber-crt',
    name: 'Amber CRT',
    colors: {
      bg: '#1e1810',
      surface: '#2c2214',
      sidebar: '#16100a',
      border: '#66481e',
      text: '#ffd9a3',
      textDim: '#cca86e',
      accent: '#ffb347',
      accent2: '#ffe08a',
      accent3: '#ff7a00',
      success: '#ffd166',
      warning: '#ffb347',
      error: '#ff7a59',
    },
    terminalColors: {
      background: '#1e1810',
      foreground: '#ffd9a3',
      cursor: '#ffb347',
      cursorAccent: '#1e1810',
      selectionBackground: '#ffb34733',
      black: '#16100a',
      red: '#ff8b73',
      green: '#ffd166',
      yellow: '#ffe08a',
      blue: '#ffbe69',
      magenta: '#ff9b54',
      cyan: '#ffd39b',
      white: '#ffd9a3',
      brightBlack: '#906d42',
      brightRed: '#ffb29f',
      brightGreen: '#ffe09a',
      brightYellow: '#ffedb0',
      brightBlue: '#ffd18b',
      brightMagenta: '#ffbf8d',
      brightCyan: '#ffe5c4',
      brightWhite: '#fff6e8',
    },
  },
  {
    id: 'zero-lux',
    name: 'Zero Lux',
    colors: {
      bg: '#0e0e0e',
      surface: '#181818',
      sidebar: '#080808',
      border: '#363636',
      text: '#fafafa',
      textDim: '#a5a5a5',
      accent: '#ffffff',
      accent2: '#cfcfcf',
      accent3: '#7dd3fc',
      success: '#7af0b4',
      warning: '#f5d06f',
      error: '#ff8a8a',
    },
    terminalColors: {
      background: '#0e0e0e',
      foreground: '#fafafa',
      cursor: '#ffffff',
      cursorAccent: '#0e0e0e',
      selectionBackground: '#ffffff22',
      black: '#080808',
      red: '#ff8a8a',
      green: '#7af0b4',
      yellow: '#f5d06f',
      blue: '#d9d9d9',
      magenta: '#efefef',
      cyan: '#bfefff',
      white: '#fafafa',
      brightBlack: '#787878',
      brightRed: '#ffb0b0',
      brightGreen: '#aef7cd',
      brightYellow: '#f8df9d',
      brightBlue: '#ececec',
      brightMagenta: '#ffffff',
      brightCyan: '#def7ff',
      brightWhite: '#ffffff',
    },
  },
]

export function getTheme(id: string): Theme {
  return themes.find(t => t.id === id) || themes[0]
}

export function applyTheme(theme: Theme): void {
  const root = document.documentElement
  const c = theme.colors
  root.style.setProperty('--ghost-bg', c.bg)
  root.style.setProperty('--ghost-surface', c.surface)
  root.style.setProperty('--ghost-sidebar', c.sidebar)
  root.style.setProperty('--ghost-border', c.border)
  root.style.setProperty('--ghost-text', c.text)
  root.style.setProperty('--ghost-text-dim', c.textDim)
  root.style.setProperty('--ghost-accent', c.accent)
  root.style.setProperty('--ghost-accent-2', c.accent2)
  root.style.setProperty('--ghost-accent-3', c.accent3)
  root.style.setProperty('--ghost-success', c.success)
  root.style.setProperty('--ghost-warning', c.warning)
  root.style.setProperty('--ghost-error', c.error)
}
